### ISSUE TITLE
site /sk/ucty/google/login/ doesn't return 404 on zdruzenie.strom.sk

### ISSUE THREAD

**Issue by rtrembecky** [tbabej/roots#25] opened 2015-11-22 16:10 UTC
Internal Server Error: /sk/ucty/google/login/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/roots-env/lib/python2.7/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 55, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/roots-env/lib/python2.7/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 78, in dispatch
    app = provider.get_app(self.request)
  File "/var/www/roots-env/lib/python2.7/site-packages/allauth/socialaccount/providers/base.py", line 36, in get_app
    return SocialApp.objects.get_current(self.id)
  File "/var/www/roots-env/lib/python2.7/site-packages/allauth/socialaccount/models.py", line 31, in get_current
    provider=provider)
  File "/usr/lib64/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 357, in get
    self.model._meta.object_name)
DoesNotExist: SocialApp matching query does not exist.

**Comment by tbabej** [comment] 2016-01-19 14:49
Duplicate of #24.

**Closed by tbabej** 2016-01-19 14:49 UTC
